### ISSUE TITLE
failed to run leetgo init

### ISSUE THREAD

**Issue by ismdeep** [j178/leetgo#92] opened 2023-02-03 07:29 UTC
```
[INFO]  global config file created: file=/home/ljiang/.config/leetgo/config.yaml
[INFO]  project config file created: file=leetgo.yaml
Error: open /home/ljiang/.config/leetgo/cache/leetcode-questions.db: no such file or directory
```

**Comment by j178** [comment] 2023-02-03 07:43
Hi, I can't reproduce this on my side actually.

May I ask what's the version you are using? Are you building from source with `CGO_ENABLED=1`?
I am asking because from your error, the cache file is `leetcode-questions.db`, which is only possible when you build it with cgo enabled.

**Comment by ismdeep** [comment] 2023-02-03 07:47
By default, there is no `~/.config/leetgo` directory on the system. However, when you run the `leetgo init` command, the `~/.config/leetgo` directory is automatically created but not the `~/.config/leetgo/cache` directory.

**Comment by j178** [comment] 2023-02-03 07:50
Right, we do create the cache directory during init, but only for the default JSON cache implementation:
https://github.com/j178/leetgo/blob/ba77f558549cc8e0a7a1ce7d680fef1b32799067/leetcode/cache_json.go#L85-L89
not in the sqlite implementation.

Thanks for your report.

**Comment by ismdeep** [comment] 2023-02-03 07:53
You could merge my pull request to solve the bug.

**Comment by j178** [comment] 2023-02-03 07:57
merged, thanks.

**Closed by j178** 2023-02-03 07:57 UTC
